export enum FormInputType {
    Text = 'text',
    Password = 'password',
    Email = 'email',
    Number = 'number',
    Date = 'date',
    Checkbox = 'checkbox',
    Radio = 'radio',
    Submit = 'submit',
    Reset = 'reset',
    Button = 'button',
    Color = 'color',
    File = 'file',
    Hidden = 'hidden',
    Image = 'image',
    Range = 'range',
    Search = 'search',
    Tel = 'tel',
    Url = 'url',
    Week = 'week'
}